app/home_page/__init__.py
from flask import Blueprint

home_page = Blueprint(
    "home_page",
    __name__,
    template_folder="templates",
    static_folder="static"
)

from . import routes

app/home_page/routes.py
from flask import Blueprint, render_template
from . import home_page

@home_page.route("/")
def index():
    return render_template('base.html')

app/home_page/templates/base.html
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{ "Ti-Labs" }}</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='css/style.css') }}">
</head>
<body>
    <nav>
        <a href="{{ url_for('home_page.index') }}">Home</a>
    </nav>

    {% block content %}{% endblock %}

    {% block scripts %}{% endblock %}
</body>
</html>

app/home_page/templates/home.html
{% extends "base.html" %}

{% block content %}

<h1>Welcome to Ti Labs</h1>
<p>Select a mini-site: </p>

<div class = "menu">
    <a href="{{ url_for('tip_calculator.index') }}">Tip Calculator</a>
    <a href="{{ url_for('car_maintenance.index') }}">Car Maintenance</a>
    <a href="{{ url_for('expense_tracker.index') }}">Expense Tracker</a>
</div>

{% endblock %}

app/home_page/templates/index.html
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{ "Ti-Labs" }}</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='css/style.css') }}">
</head>
<body>
    <nav>
        <a href="{{ url_for('index') }}">Home</a>
    </nav>

    {% block content %}{% endblock %}

    {% block scripts %}{% endblock %}
</body>
</html>